### ISSUE TITLE
[RockTheVote.as] Add support for mapvote.cfg

### ISSUE THREAD

**Issue by incognico** [MrOats/AngelScript_SC_Plugins#10]
Add support for mapvote.cfg, it has different syntax.

Currently I'm using the following ugly hack:

A symlink of svencoop/mapvote.cfg to svencoop_addon/scripts/plugins/mapvote.cfg

as_command rtv.szMapListPath "scripts/plugins/mapvote.cfg"

```
    File@ file = g_FileSystem.OpenFile(g_MapList.GetString(), OpenFile::READ);

    if(file !is null && file.IsOpen())
    {

      g_Game.AlertMessage(at_console, "[RTV] Opening file!!!\n");
      while(!file.EOFReached())
      {

        string sLine;
        file.ReadLine(sLine);

        if(sLine.SubString(0,1) == "#" || sLine.IsEmpty())
          continue;

        sLine.Trim();

        if ( g_MapList.GetString() == "scripts/plugins/mapvote.cfg" )
        {
          array<string> parsed = sLine.Split(" ");

          if(parsed.length() < 2)
            continue;

          mapList.insertLast(parsed[1]);
        }
        else {
          mapList.insertLast(sLine);
        }
      }

      file.Close();
```

Very dirty this can be done better maybe even by a ccvar like 1 = mapcycle.txt, 2 = mapvote.cfg, 3 = custom string

**Comment by MrOats** [comment]
You can specify any file string you want, as long as it is in the defined "safe" areas that the Sven Coop Dev team has decided.

**Comment by incognico** [comment]
As the mapvote.cfg uses a diffrent syntax than mapcycle.txt it's not that simple. I'm going to add options and overhaul the plugin in general.
