### ISSUE TITLE
RockTheVote.as] prevent players spamming chat by using .rtv in console 

### ISSUE THREAD

**Issue by incognico** [MrOats/AngelScript_SC_Plugins#11]
As title

**Comment by MrOats** [comment]
Comment out this line:
https://github.com/MrOats/AngelScript_SC_Plugins/blob/c13b3d0491f2f291dd84df72d70fa63e063332a5/RockTheVote.as#L896

**Comment by incognico** [comment]
Fix is here: https://github.com/incognico/svencoop_plugins/blob/master/scripts/plugins/RockTheVote.as
