### ISSUE TITLE
[RockTheVote.as] Add command to list available maps

### ISSUE THREAD

**Issue by incognico** [MrOats/AngelScript_SC_Plugins#8]
Add a chat command outputting to console all maps available to vote, best alphabetically sorted.

**Comment by MrOats** [comment]
If you type nominate by itself, it brings up a list via CTextMenu. And it is in alphabetical order.

**Comment by incognico** [comment]
Fix is here: https://github.com/incognico/svencoop_plugins/blob/master/scripts/plugins/RockTheVote.as
