### ISSUE TITLE
[RockTheVote.as] Add a command to see already nominated maps

### ISSUE THREAD

**Issue by incognico** [MrOats/AngelScript_SC_Plugins#9]
Add a chat command to see the currently nominated maps.

**Comment by MrOats** [comment]
Should be easy to implement. For now, NominateMenu should remove any maps that have already been nominated.

**Comment by incognico** [comment]
Fix is here: https://github.com/incognico/svencoop_plugins/blob/master/scripts/plugins/RockTheVote.as
